name: "CD"

on:
  push:
    branches: [master]

defaults:
  run:
    working-directory: terraform

jobs:
  deploy-infra:
    name: "Deploy Infra"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@ea7b857d8a33dc2fb4ef5a724500044281b49a5e  # v1.6.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@3d8debd658c92063839bc97da5c2427100420dec  # 1.3.2

      - name: "Terraform init"
        id: init
        run: terraform init

      - name: "Terraform apply"
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_landing_page_prod_postgres_dbname: ${{ secrets.TF_VAR_landing_page_prod_postgres_dbname }}
          TF_VAR_landing_page_prod_postgres_username: ${{ secrets.TF_VAR_landing_page_prod_postgres_username }}
          TF_VAR_landing_page_prod_postgres_password: ${{ secrets.TF_VAR_landing_page_prod_postgres_password }}
